// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClvC3PfKPeNRYiVhqWHElNcLltCjWY_Lg',
    appId: '1:475982991222:web:932bed9b94e33e9d26f457',
    messagingSenderId: '475982991222',
    projectId: 'doremind-a6335',
    authDomain: 'doremind-a6335.firebaseapp.com',
    storageBucket: 'doremind-a6335.appspot.com',
    measurementId: 'G-5238F6P4LE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzE8u8ic3EFSQ3QEY2Zxt_5mDe2QyLMgA',
    appId: '1:475982991222:android:006164cd6dbca69c26f457',
    messagingSenderId: '475982991222',
    projectId: 'doremind-a6335',
    storageBucket: 'doremind-a6335.appspot.com',
  );
}
