// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClvC3PfKPeNRYiVhqWHElNcLltCjWY_Lg',
    appId: '1:475982991222:web:974039d92a9e0bd526f457',
    messagingSenderId: '475982991222',
    projectId: 'doremind-a6335',
    authDomain: 'doremind-a6335.firebaseapp.com',
    storageBucket: 'doremind-a6335.appspot.com',
    measurementId: 'G-5W6MJM24SX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzE8u8ic3EFSQ3QEY2Zxt_5mDe2QyLMgA',
    appId: '1:475982991222:android:60bdce3492aa7a0426f457',
    messagingSenderId: '475982991222',
    projectId: 'doremind-a6335',
    storageBucket: 'doremind-a6335.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGKaudTFH9_QH4XoVRgPQ2VNV_PdTKoWw',
    appId: '1:475982991222:ios:df396b8666f8c1ca26f457',
    messagingSenderId: '475982991222',
    projectId: 'doremind-a6335',
    storageBucket: 'doremind-a6335.appspot.com',
    iosBundleId: 'com.example.doReMind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGKaudTFH9_QH4XoVRgPQ2VNV_PdTKoWw',
    appId: '1:475982991222:ios:df396b8666f8c1ca26f457',
    messagingSenderId: '475982991222',
    projectId: 'doremind-a6335',
    storageBucket: 'doremind-a6335.appspot.com',
    iosBundleId: 'com.example.doReMind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClvC3PfKPeNRYiVhqWHElNcLltCjWY_Lg',
    appId: '1:475982991222:web:c8ad5c194030e29526f457',
    messagingSenderId: '475982991222',
    projectId: 'doremind-a6335',
    authDomain: 'doremind-a6335.firebaseapp.com',
    storageBucket: 'doremind-a6335.appspot.com',
    measurementId: 'G-JLG056Y9TT',
  );
}
